### ISSUE TITLE
Can't get data dictionary from merged file

### ISSUE THREAD

**Issue by tk27182** [Nielson-Lab/NIH-database-pipeline#4]
Merged the files and put the merged file back in the inputs folder to try and get a data dictionary for all the variables in the master datasets I put together:
-	Returned very quickly an internal server error with the code in the terminal saying the following:

```
Exception on /scrape_NDA [POST]
Traceback (most recent call last):
  File "flask/app.py", line 2446, in wsgi_app
  File "flask/app.py", line 1951, in full_dispatch_request
  File "flask/app.py", line 1820, in handle_user_exception
  File "flask/_compat.py", line 39, in reraise
  File "flask/app.py", line 1949, in full_dispatch_request
  File "flask/app.py", line 1935, in dispatch_request
  File "run_app.py", line 2033, in scrape_NDA
  File "scrape_NDA_data_dictionary.py", line 298, in run_scraping
  File "scrape_NDA_data_dictionary.py", line 171, in get_all_data_dicts
  File "scrape_NDA_data_dictionary.py", line 92, in get_no_submission_structure
AttributeError: 'NoneType' object has no attribute 'find_all'
ERROR:run_app:Exception on /scrape_NDA [POST]
Traceback (most recent call last):
  File "flask/app.py", line 2446, in wsgi_app
  File "flask/app.py", line 1951, in full_dispatch_request
  File "flask/app.py", line 1820, in handle_user_exception
  File "flask/_compat.py", line 39, in reraise
  File "flask/app.py", line 1949, in full_dispatch_request
  File "flask/app.py", line 1935, in dispatch_request
  File "run_app.py", line 2033, in scrape_NDA
  File "scrape_NDA_data_dictionary.py", line 298, in run_scraping
  File "scrape_NDA_data_dictionary.py", line 171, in get_all_data_dicts
  File "scrape_NDA_data_dictionary.py", line 92, in get_no_submission_structure
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by tk27182** [comment]
No, after you merge files from either NDA or FITBIR, you can't get the data dictionary.

The code to scrape the data dictionaries from NDA and FITBIR depends on the name of the downloaded files, because that's how they're referenced on the database websites. 

To collect the data dictionary of all your files, put them in the `Inputs` folder and use the correct "Collect Data Dictionaries" button in the application. The application will automatically combine them into one.

Note that the data dictionaries on the databases *do not* contain descriptive statistics for each variable in your dataset, so the final data dictionary will not either. If you want descriptive statistics for each variable in your dataset, merge the files, and then use the "Get Stats" feature. You can then merge the data dictionary and stats file.
